In [17]:
import pandas as pd

In [18]:
# data_load

df = pd.read_csv('./F-Score.csv', encoding='cp949')
df

,회사명0,거래소코드1,회계연도2,[공통] 당기순손익(요약)(IFRS)3,[공통] *영업에서 창출된 현금흐름(요약)(IFRS)4,[공통]총자본순이익률(IFRS)5,[공통]부채비율(IFRS)6,PCR(최고)(IFRS)7,[공통] 보통주(IFRS)8,[공통] 우선주(IFRS)9,[공통]매출액증가율(IFRS)10,[공통]순이익증가율(IFRS),[공통]총자본회전률(IFRS),종가
0,(주)BNK금융지주,138930,Dec-11,122570.0,124597.0,NaN,NaN,NaN,193379899.0,0.0,NaN,NaN,NaN,11050.0
1,(주)BNK금융지주,138930,Dec-12,80435.0,88935.0,2.36,24.19,35.54,193379899.0,0.0,0.00,0.00,0.03,13200.0
2,(주)BNK금융지주,138930,Dec-13,61140.0,78050.0,1.77,28.12,51.66,193379899.0,0.0,-9.17,-23.99,0.03,16000.0
3,(주)BNK금융지주,138930,Dec-14,356414.0,378639.0,8.86,27.84,10.75,234379899.0,0.0,284.69,482.95,0.10,14500.0
4,(주)BNK금융지주,138930,Dec-15,6371.0,32479.0,0.13,28.35,0.00,255935246.0,0.0,-83.81,-98.21,0.01,8420.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23040,흥아해운(주),3280,Dec-18,-96954.0,-16131.0,-11.99,1279.81,0.00,175643430.0,0.0,-9.71,0.00,0.87,402.0
23041,흥아해운(주),3280,Dec-19,-52551.0,-6401.0,-8.99,2092.30,0.00,112112392.0,0.0,-86.19,0.00,0.17,481.0
23042,흥아해운(주),3280,Dec-20,-37398.0,272.0,-11.14,0.00,0.00,116732559.0,0.0,-12.24,0.00,0.25,258.0
23043,흥아해운(주),3280,Dec-21,15770.0,3129.0,5.92,129.31,0.00,240424899.0,0.0,-4.37,0.00,0.31,2700.0
23044,흥아해운(주),3280,Dec-11,-22898.0,18303.0,-4.33,388.47,21.62,70713430.0,0.0,12.26,0.00,1.25,729.0

In [19]:
df.head()

,회사명0,거래소코드1,회계연도2,[공통] 당기순손익(요약)(IFRS)3,[공통] *영업에서 창출된 현금흐름(요약)(IFRS)4,[공통]총자본순이익률(IFRS)5,[공통]부채비율(IFRS)6,PCR(최고)(IFRS)7,[공통] 보통주(IFRS)8,[공통] 우선주(IFRS)9,[공통]매출액증가율(IFRS)10,[공통]순이익증가율(IFRS),[공통]총자본회전률(IFRS),종가
0,(주)BNK금융지주,138930,Dec-11,122570.0,124597.0,NaN,NaN,NaN,193379899.0,0.0,NaN,NaN,NaN,11050.0
1,(주)BNK금융지주,138930,Dec-12,80435.0,88935.0,2.36,24.19,35.54,193379899.0,0.0,0.00,0.00,0.03,13200.0
2,(주)BNK금융지주,138930,Dec-13,61140.0,78050.0,1.77,28.12,51.66,193379899.0,0.0,-9.17,-23.99,0.03,16000.0
3,(주)BNK금융지주,138930,Dec-14,356414.0,378639.0,8.86,27.84,10.75,234379899.0,0.0,284.69,482.95,0.10,14500.0
4,(주)BNK금융지주,138930,Dec-15,6371.0,32479.0,0.13,28.35,0.00,255935246.0,0.0,-83.81,-98.21,0.01,8420.0

In [20]:
df.columns = ['name', 'code', "year", 'net_p_l', 'cash_flow', 'ROI', 'debt_r', 'PCR', 'stock', 'f_stock', 'sales_r', 'net_r', 'total_cap' ,'close']

In [21]:
df.columns

Index(['name', 'code', 'year', 'net_p_l', 'cash_flow', 'ROI', 'debt_r', 'PCR',
       'stock', 'f_stock', 'sales_r', 'net_r', 'total_cap', 'close'],
      dtype='object')

In [22]:
import numpy as np

df = df.fillna(0)
df['F_score'] = np.nan
df['F_score1'] = np.nan
df['F_score1'] = df['F_score1'].fillna(0)

company = list(df['name'].unique())
len(company)
df.columns

Index(['name', 'code', 'year', 'net_p_l', 'cash_flow', 'ROI', 'debt_r', 'PCR',
       'stock', 'f_stock', 'sales_r', 'net_r', 'total_cap', 'close', 'F_score',
       'F_score1'],
      dtype='object')

In [23]:
#01 전년 당기순이익 흑자
df.loc[df['net_p_l'] > 0, 'F_score'] = 1
df.loc[df['net_p_l'] < 0, 'F_score'] = 0

In [24]:
#02 전년 영업활동현금흐름 흑자
df.loc[df['cash_flow'] > 0, 'F_score'] += 1
df.loc[df['cash_flow'] < 0, 'F_score'] = 0

In [25]:
#03 (현재 ROA > 전년 ROA)>>> 현재 ROI > 전년 ROI
for i in company :
    df_a = df[df['name'] == i]
    for j in range(len(df_a)-1):
        df.iloc[j+1,-1] = (df.iloc[j+1,5] - df.iloc[j,5])
df.loc[df['F_score1'] > 0, 'F_score'] += 1

In [26]:
#04 현재 영업현금흐름 > 순이익 순이익 < 현금흐름
for i in company :
    df_a = df[df['name'] == i]
    for j in range(len(df_a)-1):
        df.iloc[j+1,-1] = (df.iloc[j,3] - df.iloc[j,4])
df.loc[df['F_score1'] > 0, 'F_score'] += 1

In [27]:
#05 현재 부채비율 < 전년 부채비율
for i in company :
    df_a = df[df['name'] == i]
    for j in range(len(df_a)-1):
        df.iloc[j+1,-1] = (df.iloc[j+1,6] - df.iloc[j,6])
df.loc[df['F_score1'] < 0, 'F_score'] += 1

In [28]:
#06 (현재 유동비율 > 전년 유동비율) >>> 금년 PCR < 전년 PCR
for i in company :
    df_a = df[df['name'] == i]
    for j in range(len(df_a)-1):
        df.iloc[j+1,-1] = (df.iloc[j+1,7] - df.iloc[j,7])
df.loc[df['F_score1'] < 0, 'F_score'] += 1

In [29]:
#07 전년 신주발행이력 X
for i in company :
    df_a = df[df['name'] == i]
    for j in range(len(df_a)-1):
        df.iloc[j+1,-1] = (df.iloc[j+1,8] - df.iloc[j,8])
df.loc[df['F_score1'] <= 0, 'F_score'] += 1

In [30]:
#08 (매출총이익률 전년대비증가) >>> 매출액증가율 < 순이익증가율
for i in company :
    df_a = df[df['name'] == i]
    for j in range(len(df_a)-1):
        df.iloc[j+1,-1] = (df.iloc[j,11] - df.iloc[j,10])
df.loc[df['F_score1'] > 0, 'F_score'] += 1

In [31]:
#09 (자산회전율 전년대비증가) >>> 총자본회전율 전년대비증가
for i in company :
    df_a = df[df['name'] == i]
    for j in range(len(df_a)-1):
        df.iloc[j+1,-1] = (df.iloc[j+1,12] - df.iloc[j,12])
df.loc[df['F_score1'] > 0, 'F_score'] += 1

In [33]:
df.head(12)

,name,code,year,net_p_l,cash_flow,ROI,debt_r,PCR,stock,f_stock,sales_r,net_r,total_cap,close,F_score,F_score1
0,(주)BNK금융지주,138930,Dec-11,122570.0,124597.0,0.00,0.00,0.00,193379899.0,0.0,0.00,0.00,0.00,11050.0,3.0,0.00
1,(주)BNK금융지주,138930,Dec-12,80435.0,88935.0,2.36,24.19,35.54,193379899.0,0.0,0.00,0.00,0.03,13200.0,5.0,0.03
2,(주)BNK금융지주,138930,Dec-13,61140.0,78050.0,1.77,28.12,51.66,193379899.0,0.0,-9.17,-23.99,0.03,16000.0,3.0,0.00
3,(주)BNK금융지주,138930,Dec-14,356414.0,378639.0,8.86,27.84,10.75,234379899.0,0.0,284.69,482.95,0.10,14500.0,6.0,0.07
4,(주)BNK금융지주,138930,Dec-15,6371.0,32479.0,0.13,28.35,0.00,255935246.0,0.0,-83.81,-98.21,0.01,8420.0,4.0,-0.09
5,(주)BNK금융지주,138930,Dec-16,76019.0,-6901.0,1.38,26.83,36.66,325935246.0,0.0,99.25,1093.17,0.02,8680.0,3.0,0.01
6,(주)BNK금융지주,138930,Dec-17,131203.0,46895.0,2.25,26.96,19.68,325935246.0,0.0,42.36,72.59,0.03,9420.0,8.0,0.01
7,(주)BNK금융지주,138930,Dec-18,29074.0,-32092.0,0.49,26.58,125.90,325935246.0,0.0,-45.03,-77.84,0.02,7330.0,4.0,-0.01
8,(주)BNK금융지주,138930,Dec-19,91575.0,-87407.0,1.50,23.17,84.35,325935246.0,0.0,57.09,214.98,0.03,7660.0,6.0,0.01
9,(주)BNK금융지주,138930,Dec-20,250300.0,-18606.0,4.01,22.93,9.75,325935246.0,0.0,94.22,173.33,0.05,5680.0,7.0,0.02
10,(주)BNK금융지주,138930,Dec-21,206303.0,-41553.0,3.13,29.96,14.68,325935246.0,0.0,-10.10,-17.58,0.04,8400.0,3.0,-0.01
11,(주)CMG제약,58820,Dec-11,-1264.0,-2353.0,-4.66,50.61,0.00,43693200.0,0.0,56.40,0.00,0.65,785.0,1.0,0.00